### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by mpearmain** [anilshetty538/NLP2SQL#1]
Looks like an interesting project, can you add a README to get a better understanding of the codebase

**Comment by anilhirehalli** [comment]
@mpearmain  we are working on it we will update readme very soon.
Thank you

**Comment by AshRK1997** [comment]
Hi @mpearmain, sorry for the delay. I have added the readme, let me know if you need something else.

**Comment by AshRK1997** [comment]
I will now close this issue now, please email me at reachashrk@gmail.com for any further clarification.
